### ISSUE TITLE
Compile with vs2022 17.0.5 error

### ISSUE THREAD

**Issue by Endt4sk** [DevExpress/winui-demos#4]
error NU1102: Unable to find package DevExpress.Reporting.Core with version (>= 21.2.3)

I can't find the package at Nuget.org and nuget.devexpress.com

**Comment by AlexGoOn** [comment]
Hello,
You need to access reporting libraries to build the project. If you don't have an active [Reporting subscription](https://www.devexpress.com/subscriptions/reporting/), you can start a trial as described at [Trial .NET Controls Via NuGet](https://docs.devexpress.com/GeneralInformation/120534/installation/install-devexpress-controls-using-nuget-packages/net-core-controls-via-nuget). We will add this information to the repository description.
