### ISSUE TITLE
Please help with WinUI Demos Compile Errors

### ISSUE THREAD

**Issue by jmscraig** [DevExpress/winui-demos#5]
Greetings. 

Yesterday I installed the WinUI 3 packages and began a 30 day trial of your full offering. 

I am eager to work with this nice demo repository.    

I am using Visual Studio 2022 on a Windows machine.  How would I resolve these compile errors.  
A number of cycles of obj-bin purge, Clean, Build & Rebuild have not helped.  
The DevExpress Project Converter does not recognize a project in these directories.
I successfully compiled a larger application built using DevExpress components that did not include DevExpress.WinUI

When just the first compile error was visible ( NU1603 )  a manual edit of Directory.Build.props seemed to resolve it but then the 'grid' not found errors appeared. 

How do I ensure a reliable compile.  

Thank you!

===Example Log Output
Build started...
Build started...
1>------ Build started: Project: FeatureDemo, Configuration: Release x64 ------
1>C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\GridDemo\NewItemRowModule.xaml.cs(15,69,15,73): error CS0103: The name 'grid' does not exist in the current context
1>C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\GridDemo\DataFilteringModule.xaml.cs(10,13,10,17): error CS0103: The name 'grid' does not exist in the current context
1>C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\GridDemo\DataFilteringModule.xaml.cs(18,13,18,17): error CS0103: The name 'grid' does not exist in the current context
1>C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\GridDemo\DataFilteringModule.xaml.cs(20,57,20,61): error CS0103: The name 'grid' does not exist in the current context
1>Done building project "FeatureDemo.csproj" -- FAILED.
2>------ Skipped Publish: Project FeatureDemo, Configuration: Release x64 ------
2> 
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

=== Errors List items
1) Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	NU1603	FeatureDemo depends on DevExpress.Reporting.Core (>= 21.2.3) but DevExpress.Reporting.Core 21.2.3 was not found. An approximate best match of DevExpress.Reporting.Core 21.2.5 was resolved.	FeatureDemo	C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo	C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\FeatureDemo.csproj	1	

2) Severity	Code	Description	Project	Path	File	Line	Suppression State
Error	CS0103	The name 'grid' does not exist in the current context	FeatureDemo	C:\Users\Ja
![DevExpress-WinUI-Demos-Compile-Errors-Feb2022](https://user-images.githubusercontent.com/15313578/152929149-0f782d1e-9851-4ea4-a497-ea8835994100.JPG)
sCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\GridDemo	C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\GridDemo\DataFilteringModule.xaml.cs	10	Active

3) Severity	Code	Description	Project	Path	File	Line	Suppression State
Error		Specified EntryPointExe 'FeatureDemo.exe' was not found in the project outputs.	FeatureDemo (Package)	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\DesktopBridge	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets	744

**Comment by AlexGoOn** [comment]
Hello James,
Thank you for your interest in our WinUI controls. We changed the target version for the _DevExpress.Reporting.Core_ package. Now you should be able to access it using the trial NuGet feed. As for the other two errors, they should disappear after rebuilding the project. If this doesn't help, try reopening the Visual Studio solution. 

P.S. We would be happy to help you address your needs with our controls. If you get a minute, please describe what controls and features are most important for you and what UI you would like to create (you can send us your wireframe if you have one). We will try to give you recommendations and shorten your learning curve. You can create a private ticket in our [Support Center](http://www.devexpress.com/ask) if you would like to share sensitive information.
