### ISSUE TITLE
Please update the wonder WinUI-demos to work with current DevExpress WinUI download.

### ISSUE THREAD

**Issue by jmscraig** [DevExpress/winui-demos#6]
Submitting a second pragmatic companion issue request for the longer term fix so others do not have as much trouble with the demos. 

Please update the wonder WinUI-demos to work with current DevExpress WinUI download.

Example error: 

Severity Code Description Project Path File Line Suppression State
Error NU1603 FeatureDemo depends on DevExpress.Reporting.Core (>= 21.2.3) but DevExpress.Reporting.Core 21.2.3 was not found. An approximate best match of DevExpress.Reporting.Core 21.2.5 was resolved. FeatureDemo C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo C:\Users\JasCr\source\WinUI3\DevEx-WinUI-Demos\src\FeatureDemo\FeatureDemo\FeatureDemo.csproj 1

Thanks!

**Comment by AlexGoOn** [comment]
Hello James,
We changed the target version for the DevExpress.Reporting.Core package. Now you should be able to access it using the [trial](https://www.devexpress.com/Products/Try/) NuGet feed.

Thanks,
Alex
